# compose.ymlのバージョンを使用"3"が広く扱われる
version: '3' 
services:
  react-app:
    # コンテナ名
    container_name: wordwolf_reacp_app
    env_file: 
      - .env
    build:
      # Reactアプリケーションのファイルが配置されているディレクトリを指定
      context: ./frontend/react_project
      # ./react_project ディレクトリ内にある Dockerfile を使ってコンテナをビルド
      dockerfile: Dockerfile 
    ports:
      # http://localhost:3000にアクセスすると、Reactアプリケーションがコンテナ内で実行される開発サーバーに接続できる
      - "${REACT_PORT}:3000"
    # ホスト側のファイルシステムとコンテナ内のファイルシステムを同期させるために使用
    volumes:
      # ホストのreact_projectをマウント
      - ./frontend/react_project:/react_project
      - /react_project/node_modules
    stdin_open: true
    tty: true
    depends_on:
      - django-app
  django-app:
    container_name: wordwolf_django_app
    env_file: 
      - .env
    build:
      context: ./backend 
      dockerfile: Dockerfile 
    ports:
      - "${DJANGO_PORT}:8000"
    volumes:
      - ./backend:/backend 
    depends_on:
      - ${MYSQL_APP_NAME}
  mysql-app:
    image: mysql:${MYSQL_VERSION}
    container_name: wordwolf_db
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - ./mysql_data:/var/lib/mysql